config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new', as: 'register'

  get '/login', to: 'sessions#new', as: 'login'
  get '/profile', to: 'sessions#show', as: 'profile'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :posts do
    resources :comments, only: [:create]
  end
  get '/posts/:id/confirm_delete', to: 'posts#confirm_delete', as: 'post_confirm_delete'

  resources :users, except: [:index]
  get '/users/:id/confirm_delete', to: 'users#confirm_delete', as: 'user_confirm_delete'

  resources :categories, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, length: { minimum: 3, maximum: 15 }, presence: true, uniqueness: true

  before_save :sanitize_name

  def sanitize_name
    self.name = self.name.downcase.parameterize.gsub(/\d/, '')
  end

  def to_param
    self.name
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :body, presence: true

  before_save :generate_slug

  def generate_slug
    slug = self.title.downcase.parameterize

    if Post.exists?(slug: slug)
      postfix = 1

      loop do
        slug = "#{slug}-#{postfix}"
        break unless Post.exists?(slug: slug)
        postfix += 1
        slug = self.title.downcase.parameterize
      end
    end

    self.slug = slug
  end

  def to_param
    self.slug
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_secure_password

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 15 }, format: { without: /\s/, message: "can't have spaces" }
  validates :email, presence: true, uniqueness: true

  before_save :generate_slug

  def generate_slug
    slug = self.username.downcase.parameterize

    if User.exists?(slug: slug)
      postfix = 1

      loop do
        slug = "#{slug}-#{postfix}"
        break unless User.exists?(slug: slug)
        postfix += 1
        slug = self.username.downcase.parameterize
      end
    end

    self.slug = slug
  end

  def to_param
    self.slug
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    if !logged_in?
      flash[:error] = "You need to be logged in to access that resource"
      redirect_to root_path
    end
  end

  def require_logout
    redirect_to root_path if logged_in?
  end

  def set_back_path
    @back_path = request.referer
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, except: [:show]

  def show
    @category = Category.find_by(name: params[:id])
    @posts = @category.posts
  end

  def new
    set_back_path
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))

    if @category.save
      flash[:notice] = "Category created"
      redirect_to new_category_path
    else
      render :new
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.new(params.require(:comment).permit(:body))
    @comment.author = current_user

    if @comment.save
      flash[:notice] = "Comment posted"
      redirect_to @post
    else
      render "posts/show"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :confirm_delete, :destroy]
  before_action :post_params, only: [:create, :update]
  before_action :require_login, except: [:index, :show]
  before_action :require_author, only: [:edit, :confirm_delete, :destroy]
  before_action :set_back_path, only: [:new, :edit, :confirm_delete]

  def index
    @posts = Post.all.sort_by(&:created_at).reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      flash[:notice] = "Post created"
      redirect_to @post
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post updated"
      redirect_to @post
    else
      render :edit
    end
  end

  def confirm_delete

  end

  def destroy
    @post.destroy
    flash[:notice] = "Post deleted"
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, category_ids: [])
  end

  def require_author
    if @post.author != current_user
      flash[:error] = "Access denied"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:show, :destroy]
  before_action :require_logout, except: [:show, :destroy]

  def new
    session[:back_path] = request.referer
  end

  def show
    @user = current_user

    render 'users/show'
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to session[:back_path]
    else
      flash[:error] = "Username or password not found"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :show]
  before_action :require_logout, only: [:new]
  before_action :set_user, only: [:show, :edit, :update, :confirm_delete, :destroy]
  before_action :require_authorized_user, only: [:edit, :confirm_delete, :destroy]
  before_action :set_back_path, only: [:new, :edit, :confirm_delete]

  def new
    @user = User.new
  end

  def show

  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Account created."
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def confirm_delete

  end

  def destroy
    session.delete(:user_id)
    @user.destroy
    flash[:notice] = "Account deleted"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def user_params
    params.require(:user).permit!
  end

  def require_authorized_user
    if @user != current_user
      flash[:error] = "Access denied"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category %></span>

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
      <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      </div>

      <%= f.submit "Add category", class: "btn btn-primary" %>
      <%= link_to "Cancel", @back_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "shared/page_title", title: "Add new category" %>
<%= render "form" %>

app/views/categories/show.html.erb
<%= render "shared/page_title", title: "Category: #{@category.name}" %>
<%= render @posts %>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <p><%= comment.body %></p>
        <hr>
        <small>posted by <%= link_to comment.author.username, user_path(comment.author) %> on <%= comment.created_at %></small>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comments_table_view.html.erb
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Post</th>
      <th>Comment</th>
    </tr>
  </thead>
  <tbody>
    <% comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.post.title, comment.post %></td>
        <td><%= link_to "#{truncate(comment.body, length: 30)}", comment.post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
  <%= render "shared/errors", errors: @comment.errors.full_messages %>
<% end %>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, "Comment" %>
    <%= f.text_area :body, class: "form-control comment" %>
  </div>

  <%= f.submit "Post comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_categories.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% Category.all.sort_by(&:name).each do |category| %>
      <li><%= link_to category.name, category %></li>
    <% end %>
    <% if logged_in? %>
      <li class="divider" role="separator"></li>
      <li><%= link_to "Add new category", new_category_path %></li>
    <% end %>
  </ul>
</li>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header_logged_in.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to "Create post", new_post_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to profile_path do %>
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          View Profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path, method: :delete do %>
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          Logout
        <% end %>
      </li>
    </ul>
   </li>
</ul>

app/views/layouts/_header_logged_out.html.erb
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to "Register", register_path %></li>
  <li><%= link_to "Log in", login_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>The Epic Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" aria-expanded="false" data-target="#menu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "EpicBlog", root_path, class: "navbar-brand" %>
          <p class="navbar-text">A blog of epic proportions</p>
        </div>
        <div class="collapse navbar-collapse" id="menu">
          <ul class="nav navbar-nav">
            <%= render "layouts/categories" %>
          </ul>
          <% if logged_in? %>
            <%= render "layouts/header_logged_in" %>
          <% else %>
            <%= render "layouts/header_logged_out" %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_edit_del_links.html.erb
<% if post.author == current_user %>
  <p><small><%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post_confirm_delete_path(post) %></small></p>
<% end %>

app/views/posts/_form.html.erb
<%= render "shared/errors", errors: @post.errors if @post.errors.any? %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class="form-group">
        <p class="help-block">Categories:</p>
      </div>

      <div class="checkbox">
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
          <%= b.label do %>
            <%= b.check_box %>
            <%= b.text %>
          <% end %>
        <% end %>
      </div>

      <%= f.submit "Publish", class: "btn btn-success" %>
      <%= link_to "Cancel", @back_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="row post">
  <div class="col-md-6 col-md-offset-3 well">
    <div class="row hidden-xs">
      <div class="col-md-12">
        <p>
          <%= render post.categories %>
        </p>
      </div>
    </div>
    <p class="lead"><%= link_to post.title, post %></p>
    <p><%= sanitize truncate(post.body, length: 70) %></p>
    <hr>
    <%= link_to "#{pluralize(post.comments.count, 'comment')}", post %>
    <hr>
    <%= render "posts/edit_del_links", post: post %>
    <small>posted by <%= link_to post.author.username, user_path(post.author) %> on <%= post.created_at %></small>
  </div>
</div>

app/views/posts/_posts_table_view.html.erb
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Published on</th>
      <% if logged_in? %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.created_at %></td>
        <td><%= render "posts/edit_del_links", post: post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/confirm_delete.html.erb
<%= render "shared/page_title", title: "Please confirm ..." %>
<div class="row">
  <div class="col-md-8 col-md-offset-2 well">
    <p class="lead">Are you sure you want to delete the post titled <strong><%= @post.title %></strong>?</p>
    <hr>
    <div class="row">
      <div class="col-md-1"><%= link_to "Yes", @post, method: :delete, class: "btn btn-danger" %></div>
      <div class="col-md-1"><%= link_to "No", @back_path, class: "btn btn-default" %></div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "shared/page_title", title: "Edit post" %>
<%= render "form" %>

app/views/posts/index.html.erb
<%= render "shared/page_title", title: "All Posts" %>
<%= render @posts %>

app/views/posts/new.html.erb
<%= render "shared/page_title", title: "New post" %>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @post.title %> <small>by: <%= link_to @post.author.username, user_path(@post.author) %></small></h3>
        <p class="hidden-xs"><small>categories: <%= render @post.categories %></small></p>
        </div>
      <div class="panel-body"><%= simple_format @post.body %></div>
      <% if @post.author == current_user %>
        <div class="panel-footer"><%= render "edit_del_links", post: @post %></div>
      <% end %>
    </div>
  </div>
</div>
<hr>
<% if logged_in? %>
  <div class="row">
    <div class="col-md-6">
      <%= render "comments/form" %>
    </div>
  </div>
<% end %>
<div class="row comments">
  <div class="col-md-6">
    <% if @post.comments.empty? %>
      <p class="lead">No comments</p>
    <% else %>
      <%= render @post.comments %>
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="alert alert-danger alert_dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      There were some errors:
      <ul>
        <% errors.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_page_title.html.erb
<p class="lead"><%= title %></p>
<hr>

app/views/users/_form.html.erb
<%= render "shared/errors", errors: @user.errors.full_messages if @user.errors.any? %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>

      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", @back_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/confirm_delete.html.erb
<%= render "shared/page_title", title: "Please confirm ..." %>
<div class="row">
  <div class="col-md-8 col-md-offset-2 well">
    <p class="lead">Are you sure you want to delete the user <strong><%= @user.username %></strong>?</p>
    <hr>
    <div class="row">
      <div class="col-md-1"><%= link_to "Yes", @user, method: :delete, class: "btn btn-danger" %></div>
      <div class="col-md-1"><%= link_to "No", @back_path, class: "btn btn-default" %></div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "shared/page_title", title: "Edit profile" %>
<%= render "form" %>

app/views/users/new.html.erb
<%= render "shared/page_title", title: "Register" %>
<%= render "form" %>

app/views/users/show.html.erb
<%= render "shared/page_title", title: "Profile" %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="lead"><%= @user.username %></p>
        <p><small><strong>First name:</strong> <%= @user.first_name %></small></p>
        <p><small><strong>Last name:</strong> <%= @user.last_name %></small></p>
        <p><small><strong>Email:</strong> <%= @user.email %></small></p>
        <% if @user == current_user %>
          <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-default" %>
          <%= link_to "Delete account", user_confirm_delete_path(@user), class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Posts <span class="badge"><%= @user.posts.count %></span></a></li>
      <li role="presentation"><a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments <span class="badge"><%= @user.comments.count %></span></a></li>
    </ul>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="profile"><%= render "posts/posts_table_view", posts: @user.posts %></div>
      <div role="tabpanel" class="tab-pane" id="comments"><%= render "comments/comments_table_view", comments: @user.comments %></div>
    </div>
  </div>
</div>